name: Generate activity graph
on:
  schedule:  # Runs every 12 hours 
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        with:
          SETTING_JSON: |
            {
              "type": "normal",
              "config": {
                "github_token": "${{ secrets.GITHUB_TOKEN }}",
                "username": "axel-lois",
                "max_repos": 100,
                "exclude_repo": [],
                "exclude_lang": [],
                "background_color": "#000000",
                "foreground_color": "#8B5CF6",
                "strong_color": "#A855F7",
                "weak_color": "#1F2937",
                "radar_color": "#8B5CF6",
                "calendar_color": "#8B5CF6",
                "calendar_ring_color": "#A855F7",
                "locale": "en",
                "output_path": "./profile-3d-contrib/",
                "commit_branch": "output"
              }
            }
